# Generated by Django 4.1.1 on 2022-10-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='keycap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.keycaps'),
            preserve_default=False,
        ),
    ]
